import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Instagram, Linkedin, Menu, Phone, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { nav } from "@/lib/site-data";
import { Button } from "@/components/ui/button";

export function Header(){const [open,setOpen]=useState(false); return <header className="site-header"><div className="shell nav-row"><Link to="/" className="wordmark" aria-label="Ceasiun home"><span>C</span>CEASIUN</Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([n,to])=><Link key={to} to={to} activeProps={{className:"active"}}>{n}</Link>)}</nav><div className="nav-actions"><Button asChild size="lg"><Link to="/contact">Start a project <ArrowUpRight/></Link></Button><Button className="menu-btn" variant="ghost" size="icon" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="mobile-nav">{nav.map(([n,to])=><Link key={to} to={to} onClick={()=>setOpen(false)}>{n}</Link>)}<Link to="/careers" onClick={()=>setOpen(false)}>Careers</Link><Link to="/contact" onClick={()=>setOpen(false)}>Contact</Link></nav>}</header>}
export function Footer(){return <footer className="footer"><div className="shell footer-grid"><div><Link to="/" className="wordmark"><span>C</span>CEASIUN</Link><p>Ceasiun, your digital growth partner.</p></div><div><b>Navigate</b>{nav.map(([n,to])=><Link key={to} to={to}>{n}</Link>)}<Link to="/careers">Careers</Link></div><div><b>Connect</b><a href="tel:+923140262087"><Phone/>0314 0262087</a><a href="https://linkedin.com/company/ceasiun" target="_blank" rel="noreferrer"><Linkedin/>LinkedIn</a><a href="https://instagram.com/ceasiun" target="_blank" rel="noreferrer"><Instagram/>Instagram</a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Ceasiun.</span><Link to="/admin">Admin</Link></div></footer>}
export function Layout({children}: {children:ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
export function PageIntro({eyebrow,title,copy}: {eyebrow:string,title:string,copy:string}){return <section className="page-intro grid-bg"><div className="shell"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p></div></section>}
export function SectionHead({eyebrow,title,copy}: {eyebrow:string,title:string,copy?:string}){return <div className="section-head"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function CTA(){return <section className="cta-band"><div className="shell"><p className="eyebrow">Your next move</p><h2>Build what growth needs next.</h2><Button asChild size="lg"><Link to="/contact">Talk to Ceasiun <ArrowUpRight/></Link></Button></div></section>}
export const meta=(title:string,description:string)=>({meta:[{title:`${title} — Ceasiun`},{name:"description",content:description},{property:"og:title",content:`${title} — Ceasiun`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]});
